name = "GeometricIntegratorsBase"
uuid = "71212ab4-08a2-48eb-a02b-4cbad0e9c44a"
version = "0.1.1"
authors = ["Michael Kraus <michael.kraus@ipp.mpg.de> and contributors"]

[deps]
GeometricBase = "9a0b12b7-583b-4f04-aa1f-d8551b6addc9"
GeometricEquations = "c85262ba-a08a-430a-b926-d29770767bf2"
GeometricSolutions = "7843afe4-64f4-4df4-9231-049495c56661"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
SimpleSolvers = "36b790f5-6434-4fbe-b711-1f64a1e2f6a2"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
GeometricBase = "0.12"
GeometricEquations = "0.20"
GeometricSolutions = "0.5"
LinearAlgebra = "1"
OffsetArrays = "1"
Parameters = "0.12"
SimpleSolvers = "0.5"
Unicode = "1"
julia = "1.6"

[extras]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Parameters", "SafeTestsets", "Test"]
